### PR TITLE
Upgrade ember template lint

### PR DESCRIPTION
**Pull request by mjuniper**

### CODE REVIEW

**Comment by amyrlam** [comment]
Could be bumped to 0.8.9 now ... chiming in to get rid of this error! 

image

**Comment by binhums** [comment]
Hi @mjuniper, thanks for your submission. Sorry it took so long to get to this. Have you tested the change locally?

@amyrlam you've got my back, thanks.

**Comment by mjuniper** [comment]
@binhums, yes. I actually have this installed via my branch and it seems to be working just fine.

**Comment by binhums** [comment]
Great, I'm happy to role this out.

**Comment by binhums** [comment]
Released in https://github.com/binhums/linter-ember-template/releases/tag/v0.4.0

**Comment by amyrlam** [comment]
thank you, problem solved!

**Pull request merged**
