### PR TITLE
[WIP] Update to ember-template-lint 7.x

### PR DESCRIPTION
**Pull request by bendemboski**

### CODE REVIEW

**Comment by binhums** [comment]
Fabulous ✨

**Comment by binhums** [comment]
Have you tested this?

**Comment by bendemboski** [comment]
Yes, and sadly it doesn't work yet 😢 

[This](https://github.com/rwjblue/ember-template-lint/pull/249) upstream PR should fix it. If we wanted to, in the meantime I think we could just add `strip-bom` to this plugin's dependencies to get it working, and then remove it when the upstream PR is merged and released...or would you prefer to just wait for the upstream fix?

**Comment by binhums** [comment]
I'm happy either way, if I remember rightly the plugin should default to using the version of the linter in the project root.

**Comment by gmkohler** [comment]
@bendemboski looks like [that](https://github.com/rwjblue/ember-template-lint/pull/249) PR got merged.

**Comment by bendemboski** [comment]
Updated (rebased), and tested -- it's good to go!

**Comment by binhums** [comment]
Sweet, thanks

**Comment by binhums** [comment]
Released in [v0.3.0](https://github.com/binhums/linter-ember-template/releases/tag/v0.3.0)

**Pull request merged**
